"""make user tenant optional

Revision ID: 9b10a0b522c4
Revises: 8d7471740d8f
Create Date: 2026-07-04 11:46:44.375725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b10a0b522c4'
down_revision: Union[str, Sequence[str], None] = '8d7471740d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_companies_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_companies_tenant_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MANUFACTURER', 'ADMIN', name='user_role'), nullable=False),
    sa.CheckConstraint("(role != 'ADMIN') OR (tenant_id IS NULL)", name='ck_users_admin_without_tenant'),
    sa.CheckConstraint("(role != 'MANUFACTURER') OR (tenant_id IS NOT NULL)", name='ck_users_manufacturer_requires_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_users_tenant_id_id')
    )
    op.create_table('company_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id'], ['companies.tenant_id', 'companies.id'], name='fk_company_memberships_company'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['users.tenant_id', 'users.id'], name='fk_company_memberships_user'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'company_id', name='uq_company_memberships_tenant_user_company')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_memberships')
    op.drop_table('users')
    op.drop_table('companies')
    op.drop_table('tenants')
    # ### end Alembic commands ###
